# Site settings
title: "Hacknet Extensions"
email: hacknet@mail.lv
url: https://testingunderground.github.io/extensions
description: "An alternative Hacknet extensions hosting place."
keywords: "hacknet, hacknet extensions, hacknet workshop, extensions"
skills: "An alternative place where non-Steam customers can obtain Workshop extensions."
meta_author: Avonnaire Avon

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 11063d #80B3FF
  primary-rgb: "17,6,61" #"128,179,255"
  secondary: 2c2c50 #FD6E8A
  secondary-dark: 262340 #A2122F

# Footer settings
footer:
  copyright: The General Public
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://nitter.net
  - title: facebook
    url:
  - title: stack-overflow
    url: https://stackoverflow.com/
  - title: bitbucket
    url: https://bitbucket.org/
  - title: github
    url: https://github.com/HacknetExt

# Postal address (add as many lines as necessary)
address:
  - line: PortHack.Heart
#  - line: En_Romulus

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="https://startbootstrap.com">Start Bootstrap</a>. and configured for Jekyll by <a href="https://github.com/jeromelachaud">jeromelachaud</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
